services:
  postgres:
    image: postgres:15
    container_name: pg_judicial
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: judicial_system
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_judicial
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://backend:3001

    container_name: frontend_judicial
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  pgdata:
